
exports.seed = function(knex, Promise) {

  return knex('blog').del()
    .then(function () {

      return knex('blog').insert([
        {post_name: 'Importance of Cleaning Fiber Optic Cables', date: '01/04/18', post_body: 'Fiber optic cables are becoming more and more important in our daily lives. They’re used to transmit large amounts of information very quickly, and we rely on them to maintain strong phone, cable, and internet connections. In addition, there are plenty of other practical applications for fiber optic cables, as they’ve found a home in the medical and dental industries and have even been worked into many vehicles and lighting systems. If you use fiber optic cables regularly, you should take the time to clean them so they don\’t slow down on you. If a small amount of oil from your hands or dust is able to make its way into your fiber optic cables, it could send your entire system crashing down. Something as small as a dust particle could potentially stop the light inside the cables from getting where it needs to go. That in turn could slow down the transmission of data and reduce the benefits of using fiber optic cables in the first place. You can use a dry or wet cleaning approach to cleaning your fiber optic cables, though you should avoid using wet cleaning when it comes to bulkheads and receptacles. Dry cleaning should also be the first course of action you take when cleaning fiber optic cables. You want to use a swab to gently clean your fiber optic cable connections so that data is able to pass freely through the cables and arrive at its final destination. You should never scrub connections or get too rough with them since that could cause damage. You also want to shy away from touching connectors with your bare hands since that could defeat the purpose of cleaning them in the first place. ', post_img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNQewEaK_SfdctQarL3vsE0QMbCXo0EZm997oyl_CzbGcaFX_d8w'  },
        {post_name: 'Why Fiber Optic Cables are Superior to Copper', date: '02/06/18', post_body: 'There are more and more businesses all across the country choosing to install fiber optic cables rather than traditional copper ones when setting up networks. Moreover, there are also many communication companies opting to offer their customers fiber optic cable networks. Do you know why that is? Here are some of the reasons fiber optic cables are proving to be a better option than copper. Fiber optic cables transmit data more quickly than copper. Fiber optic cables and copper cables can both be used to transmit data. However, if speed is important to you—and really, who doesn’t value speed in 2018?-then you want to use fiber optic cables. Light travels very quickly through fiber optic cables and allows them to transmit data substantially quicker than copper cables can. It’s the No. 1 reason why most businesses have turned to fiber optics in recent years. Fiber optic cables aren’t susceptible to electromagnetic interference like copper. If copper cables aren’t installed properly, they can cause electromagnetic interference, or EMI, to form. It can wreak havoc on neighboring networks and cause real issues for those who need to transmit data. With fiber optic cables, this won’t be a concern at all since they don’t cause EMI. You can use fiber optics without worrying about any interference taking place. Fiber optic cables are more durable than copper. Even though fiber optic cables are made out of glass, they are surprisingly sturdy and will not need to be replaced anywhere near as often as copper cables will. Copper cables can wear out much more quickly and require replacement. These days, most companies that have relied on copper cables in the past have replaced them with fiber optic cables as a result.', post_img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnqz17OihnxvAkK5vAOoTwjEIhLU_CLZCNNClVVh667sOgKLfp' },
        {post_name: 'How Does Fusion Splicing Work', date: '06/04/18', post_body: 'Fiber optic splicing is a technique that is used by fiber optic companies in order to bring two fiber optic cables together so that they are capable of transmitting data without skipping a beat. One of the main methods of fiber optic splicing is called fusion splicing, and it’s widely regarded as the most commonly used method of fiber optic splicing because it allows for the lowest loss and least reflectance in the newly formed fiber optic cable that has been spliced together. There are several steps that are used during fusion splicing. First, in order to prepare two fiber optic cables to be spliced, the fiber must be stripped down. A fiber optic company will remove the protective coating on the two fiber optic cables as well as any jackets or tubes that are located on them. What remains will be two bare, clean fibers that are ready for fusion splicing. Once that is finished, the fiber optic company will cleave the fibers. This creates a clean break in the fibers that wouldn’t exist if you were to simply cut the fibers. From there, the fibers are then fused together. To finish the fusing, the fiber optic company will use a fiber optic splicer to align the two pieces of fiber. After they are lined up properly, an electrical arc will then be used to melt the fibers and weld them so that the two fibers become one. After a successful fusion has been completed, a fiber optic company will finish off the splicing process by protecting the fiber optic cable that has been created. Even though the new cable should already be strong as long as everything went according to plan, there are heat shrink tubing, mechanical crimp protectors, and other products that can be used on a fiber optic cable to protect it from the elements.', post_img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrwjiabPC7gRsWmjHT909MDkazX4TaW-nKru3oeOW6cOwktMGa3w'}
      ]);
    });
};
